import Hero from '../types/hero';

const Heros: Hero[] = [
  {
    id: 1,
    name: 'Mickey Mouse',
    movie: 'Fantasia',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Mickey_Mouse.png',
    genre: 'cartoon',
  },
  {
    id: 2,
    name: 'Mike Wazowski',
    movie: 'Monsters, Inc.',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Mike_Wazowski.png',
    genre: 'cartoon',
  },
  {
    id: 3,
    name: 'SpongeBob SquarePants',
    movie: 'The SpongeBob SquarePants Movie',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/SpongeBob_SquarePants.png',
    genre: 'cartoon',
  },
  {
    id: 4,
    name: 'Garfield',
    movie: 'garfield',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Garfield.png',
    genre: 'cartoon',
  },
  {
    id: 5,
    name: 'Bugs Bunny',
    movie: 'Space Jam',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Bugs_Bunny.png',
    genre: 'cartoon',
  },
  {
    id: 6,
    name: 'Harry Potter',
    movie: "Harry Potter and the Sorcerer's Stone",
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Harry_Potter.png',
    genre: 'movie',
  },
  {
    id: 7,
    name: 'Pikachu',
    movie: 'Pokémon: The First Movie',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Pikachu.png',
    genre: 'cartoon',
  },
  {
    id: 8,
    name: 'Maverick Mitchell',
    movie: 'Top gun Maverick',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/TopGun.png',
    genre: 'movie',
  },
  {
    id: 9,
    name: 'Superman',
    movie: 'Superman',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Sumerman.png',
    genre: 'movie',
  },
  {
    id: 10,
    name: 'Skipper',
    movie: 'Penguins of madagascar',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/skiper.png',
    genre: 'cartoon',
  },
  {
    id: 11,
    name: 'Spider-Man',
    movie: 'Spider-Man: Into the Spider-Verse',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Spider-Man_Marvel.png',
    genre: 'movie',
  },
  {
    id: 12,
    name: 'Woody',
    movie: 'Toy Story',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Woody.png',
    genre: 'cartoon',
  },
  {
    id: 13,
    name: 'Elsa',
    movie: 'Frozen',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Elsa.png',
    genre: 'cartoon',
  },
  {
    id: 14,
    name: 'Batman',
    movie: 'The Dark Knight',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Batman.png',
    genre: 'movie',
  },
  {
    id: 15,
    name: 'Shrek',
    movie: 'Shrek',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Shrek.png',
    genre: 'cartoon',
  },
  {
    id: 16,
    name: 'Optimus Prime',
    movie: 'Transformers',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/images__1_-removebg-preview.png',
    genre: 'movie',
  },
  {
    id: 17,
    name: 'Thomas Shelby',
    movie: 'Stand by Me Doraemon',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/TommyShelby.png',
    genre: 'movie',
  },
  {
    id: 18,
    name: 'Iron Man',
    movie: 'Iron Man',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/images__2_-removebg-preview.png',
    genre: 'movie',
  },
  {
    id: 19,
    name: 'Harley Quinn',
    movie: 'Suicide Squad',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Harleey_Queen.png',
    genre: 'movie',
  },
  {
    id: 20,
    name: 'Deadpool',
    movie: 'Deadpool',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/DeatPool.png',
    genre: 'movie',
  },
  {
    id: 21,
    name: 'Achilles',
    movie: 'Troy',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Achilles_Troy.png',
    genre: 'movie',
  },
  {
    id: 22,
    name: 'Homer Simpson',
    movie: 'The Simpsons Movie',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Homer_Simpson.png',
    genre: 'cartoon',
  },
  {
    id: 23,
    name: 'Wall-e',
    movie: 'Wall-e',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/wall-e.jpeg',
    genre: 'cartoon',
  },
  {
    id: 24,
    name: 'Ramil',
    movie: 'Ratatuy',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Remy.png',
    genre: 'cartoon',
  },
  {
    id: 27,
    name: 'Peter Griffin',
    movie: "Family Guy: The Freakin' Sweet Collection",
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/FamilyGuy_Peter.png',
    genre: 'cartoon',
  },
  {
    id: 28,
    name: 'Stan Smith',
    movie: 'american dad',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Stan_Smith.png',
    genre: 'cartoon',
  },
  {
    id: 31,
    name: 'Stewie Griffin',
    movie: "Family Guy: The Freakin' Sweet Collection",
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Stewie_Griffin.png',
    genre: 'cartoon',
  },

  {
    id: 32,
    name: 'Olaf',
    movie: 'Frozen',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Olaf.png',
    genre: 'cartoon',
  },
  {
    id: 33,
    name: 'Darth Vader',
    movie: 'Star Wars: Episode IV - A New Hope',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Star_Wars_-_Darth_Vader.png',
    genre: 'movie',
  },
  {
    id: 34,
    name: 'Rick Sanchez',
    movie: 'Rick and Morty',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Rick_Sanchez-removebg-preview.png',
    genre: 'cartoon',
  },

  {
    id: 38,
    name: 'Art',
    movie: 'Art clown',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Art_the_Clown.png',
    genre: 'movie',
  },
  {
    id: 39,
    name: 'Scream',
    movie: 'scream',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Screem.png',
    genre: 'movie',
  },
  {
    id: 40,
    name: 'Pennywise',
    movie: 'It',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/it.png',
    genre: 'movie',
  },

  {
    id: 44,
    name: 'Gandalf',
    movie: 'The Lord of the Rings: The Fellowship of the Ring',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Gandalf.png',
    genre: 'movie',
  },
  {
    id: 47,
    name: 'Jack Sparrow',
    movie: 'Pirates of the Caribbean: The Curse of the Black Pearl',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Jack_Sparrow.png',
    genre: 'movie',
  },
  {
    id: 50,
    name: 'Twilight Sparkle',
    movie: 'My Little Pony: The Movie',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Princess_Twilight_Sparkle.png',
    genre: 'cartoon',
  },
  {
    id: 52,
    name: 'Pinkie Pie',
    movie: 'My Little Pony: The Movie',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Pinkie_Pie.png',
    genre: 'cartoon',
  },
  {
    id: 59,
    name: 'Po',
    movie: 'Panda kung fu',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Po.png',
    genre: 'cartoon',
  },
  {
    id: 60,
    name: 'Oogway',
    movie: 'Panda kung fu',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Oogway.png',
    genre: 'cartoon',
  },
  {
    id: 62,
    name: 'Elliot Alderson',
    movie: 'Mr. Robot',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Mr-Robot-removebg-preview.png',
    genre: 'movie',
  },
  {
    id: 63,
    name: 'Ryan Gosling',
    movie: 'La La Land',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Gosling.png',
    genre: 'movie',
  },
  {
    id: 64,
    name: 'Joker',
    movie: 'Movie Joker',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Joker.png',
    genre: 'movie',
  },
  {
    id: 65,
    name: 'Lebowski',
    movie: 'The Big Lebowski',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Lebovki.png',
    genre: 'movie',
  },
  {
    id: 66,
    name: 'Borat',
    movie: 'The Borat',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Borat.png',
    genre: 'movie',
  },
  {
    id: 67,
    name: 'Forest Gump',
    movie: 'The Forest Gump',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Forest_Gamp.png',
    genre: 'movie',
  },
  {
    id: 68,
    name: 'Billy',
    movie: 'Saw',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/saw.png',
    genre: 'movie',
  },
  {
    id: 69,
    name: 'Derek Zoolander',
    movie: 'Zoolander',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Zoolander.png',
    genre: 'movie',
  },
  {
    id: 70,
    name: 'Paddington',
    movie: 'The Paddington Bear',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Paddington.png',
    genre: 'movie',
  },
  {
    id: 71,
    name: 'John Wick',
    movie: 'John Wick',
    photoUrl:
      'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Jon_Uik.png?updatedAt=1708424301154',
    genre: 'movie',
  },
  {
    id: 72,
    name: 'Willi Wonka',
    movie: 'charlie and the chocolate factory',
    photoUrl: 'https://ik.imagekit.io/dk6sqsizn/MovieTalk/Willy_Wonka.png',
    genre: 'movie',
  },
];

export default Heros;
